![pandas_white.svg]()

# Brief History

* The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008. It has function to analyse, clean, explore and manipulate the data.
* It helps to work with large datasets and find the results based on statistical theories.
* Pandas can clean the messy datasets, and make them readable and relevant.
* Pandas can also delete the rows that are not relevant, or containing wrong values, like empty or NULL values. This is called the cleaning the data.

* Pandas is a labeled, columnar, Numpy-backed relational engine with a sophisticated block-oriented memory manager.

* It is a BlockManager that stores heterogeneous data in homogeneous blocks for cache efficiency.

In [ ]:
import numpy as np
import pandas as pd

print("Pandas version:", pd.__version__)
print("Numpy version:", np.__version__)

Pandas version: 2.2.2
Numpy version: 2.0.2

# pandas Data Structures

Data structures in pandas: Series and DataFrame

### Series: It is a one dimensional array-like object containing a sequence of values of the same type and an associated array of data labels, called its index.

In [ ]:
import pandas as pd

obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
print(obj.array)
print(obj.index) #pandas has default indexing start with 0 otherwise mentioned

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64
RangeIndex(start=0, stop=4, step=1)

In [ ]:
obj2 = pd.Series([4, 7, -5, 3], index=['a','b','c','d'])
obj2

a    4
b    7
c   -5
d    3
dtype: int64

* Another way to think about the Series as a fixed-length, ordered dictionary as it represents a mapping of index values to the data values.

* We can override the key values in the series values using dictionary keys.

In [ ]:
dict_data = {"x": 35000, "y": 71000, "z": 16000, "u": 5000}
obj3 = pd.Series(dict_data)
obj3

x    35000
y    71000
z    16000
u     5000
dtype: int64

In [ ]:
new_ind = ["a","b","x","y"]
dict_data = {"x": 35000, "y": 71000, "z": 16000, "u": 5000}

obj4 = pd.Series(dict_data, index = new_ind)
# Here it will replace the two values found from the original dictionary but appear as NaN(Not a Number) for other values.
obj4

a        NaN
b        NaN
x    35000.0
y    71000.0
dtype: float64

In [ ]:
print(obj3)
obj3.index = ["a","b","c","d"]
# Index alteration
print(obj3)

a    35000
b    71000
c    16000
d     5000
dtype: int64
a    35000
b    71000
c    16000
d     5000
dtype: int64

In [ ]:
import pandas as pd
import numpy as np

s = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'], name='my_series', dtype='int32')

print("--- Series Object ---")
print(s)

print("\n--- Internal Attributes ---")
print("s.values          →", type(s.values), s.values.dtype)          # NumPy array (or Arrow in some cases)
print("s.index           →", type(s.index), s.index.dtype)
print("s.name            →", s.name)
print("s.dtype           →", s.dtype)
print("s.shape           →", s.shape)
print("s.ndim            →", s.ndim)
print("s._values.base    →", s._values.base is None)   # memory view info

# ExtensionArray view (Pandas 2.x+)
print("\n--- ExtensionArray (new unified interface) ---")
print("s.array           →", type(s.array))   # IntegerArray, StringArray, etc.

--- Series Object ---
a    1
b    2
c    3
d    4
Name: my_series, dtype: int32

--- Internal Attributes ---
s.values          → <class 'numpy.ndarray'> int32
s.index           → <class 'pandas.core.indexes.base.Index'> object
s.name            → my_series
s.dtype           → int32
s.shape           → (4,)
s.ndim            → 1
s._values.base    → True

--- ExtensionArray (new unified interface) ---
s.array           → <class 'pandas.core.arrays.numpy_.NumpyExtensionArray'>

# DataFrame

* It is a rectangular table of data and contains an ordered, named collection of columns, each of which can be a different value type(numeric, string, Boolean etc.)

* It is a two dimensional labeled data structure and stores multiple homogeneous blocks smartly.

* It is a dict-like container of Series object that share the exact same index(axis = 0), with a separate container Index on axis = 1.

* It is actually not the python dict of series, but a "BlockManager" that stores data in homogeneous Numpy blocks for maximum cache efficiency and vectorized operations.

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'int_col':    [1, 2, 3],
    'float_col':  [4.1, 5.2, 6.3],
    'str_col':    ['a', 'b', 'c'],
    'cat_col':    pd.Categorical(['x', 'y', 'x'])
})

print("---- DataFrame -----")
print(df)

print("\n--- The Real Storage: BlockManager ---")
print(df._mgr)   # Shows how block manager converts all the dict containers into numpy blocks.

print("\n--- Blocks Breakdown ---")
for i, blk in enumerate(df._mgr.blocks):
    print(f"Block {i}: {type(blk).__name__} | dtype={blk.dtype} | shape={blk.shape} | "
          f"columns={df.columns[blk.mgr_locs.indexer]}")

---- DataFrame -----
   int_col  float_col str_col cat_col
0        1        4.1       a       x
1        2        5.2       b       y
2        3        6.3       c       x

--- The Real Storage: BlockManager ---
BlockManager
Items: Index(['int_col', 'float_col', 'str_col', 'cat_col'], dtype='object')
Axis 1: RangeIndex(start=0, stop=3, step=1)
NumpyBlock: slice(0, 1, 1), 1 x 3, dtype: int64
NumpyBlock: slice(1, 2, 1), 1 x 3, dtype: float64
NumpyBlock: slice(2, 3, 1), 1 x 3, dtype: object
ExtensionBlock: slice(3, 4, 1), 1 x 3, dtype: category

--- Blocks Breakdown ---
Block 0: NumpyBlock | dtype=int64 | shape=(1, 3) | columns=Index(['int_col'], dtype='object')
Block 1: NumpyBlock | dtype=float64 | shape=(1, 3) | columns=Index(['float_col'], dtype='object')
Block 2: NumpyBlock | dtype=object | shape=(1, 3) | columns=Index(['str_col'], dtype='object')
Block 3: ExtensionBlock | dtype=category | shape=(1, 3) | columns=Index(['cat_col'], dtype='object')

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': np.arange(5, dtype='int32'),
    'B': np.random.randn(5),
    'C': pd.Categorical(['x','y','x','y','x'])
})

print("Number of blocks:", len(df._mgr.blocks))

for i, blk in enumerate(df._mgr.blocks):
    arr = blk.values
    addr = hex(arr.ctypes.data) if hasattr(arr, 'ctypes') else "Arrow buffer"
    print(f"Block {i} ({blk.dtype}): address = {addr}")  # It shows that the how blocks are the stored in the memory.

Number of blocks: 3
Block 0 (int32): address = 0x3b0161f0
Block 1 (float64): address = 0x3b109280
Block 2 (category): address = Arrow buffer

In [ ]:
import pandas as pd
import numpy as np

data =  {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
         "year": [2000, 2001, 2002, 2001, 2002, 2003],
         "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
# First five rows
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [ ]:
# Last five rows
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
# dataframe columns can be rearranged and if you add extra column without data will have null values.
new_frame = pd.DataFrame(data, columns = ["year", "pop", 'state', 'debt'])
new_frame

   year  pop   state debt
0  2000  1.5    Ohio  NaN
1  2001  1.7    Ohio  NaN
2  2002  3.6    Ohio  NaN
3  2001  2.4  Nevada  NaN
4  2002  2.9  Nevada  NaN
5  2003  3.2  Nevada  NaN

In [ ]:
new_frame.columns

Index(['year', 'pop', 'state', 'debt'], dtype='object')

In [ ]:
# Retrieve column
new_frame["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [ ]:
# Rows can be retrieved using loc and iloc attributes

new_frame.loc[0]

year     2000
pop       1.5
state    Ohio
debt      NaN
Name: 0, dtype: object

In [ ]:
# Modifying the column
new_frame['debt'] = np.arange(6.)
new_frame

   year  pop   state  debt
0  2000  1.5    Ohio   0.0
1  2001  1.7    Ohio   1.0
2  2002  3.6    Ohio   2.0
3  2001  2.4  Nevada   3.0
4  2002  2.9  Nevada   4.0
5  2003  3.2  Nevada   5.0

In [ ]:
new_frame['eastern'] = new_frame['state'] == 'Ohio'
new_frame

   year  pop   state  debt  eastern
0  2000  1.5    Ohio   0.0     True
1  2001  1.7    Ohio   1.0     True
2  2002  3.6    Ohio   2.0     True
3  2001  2.4  Nevada   3.0    False
4  2002  2.9  Nevada   4.0    False
5  2003  3.2  Nevada   5.0    False

In [ ]:
del new_frame['eastern']
new_frame.columns

Index(['year', 'pop', 'state', 'debt'], dtype='object')

### Possible data inputs to the DataFrame constructor

| Type | Notes |
| :--- | :--- |
| **2D ndarray** | A matrix of data, passing optional row and column labels |
| **Dictionary of arrays, lists, or tuples** | Each sequence becomes a column in the DataFrame; all sequences must be the same length |
| **NumPy structured/record array** | Treated as the “dictionary of arrays” case |
| **Dictionary of Series** | Each value becomes a column; indexes from each Series are unioned together to form the result’s row index if no explicit index is passed |
| **Dictionary of dictionaries** | Each inner dictionary becomes a column; keys are unioned to form the row index as in the “dictionary of Series” case |
| **List of dictionaries or Series** | Each item becomes a row in the DataFrame; unions of dictionary keys or Series indexes become the DataFrame’s column labels |
| **List of lists or tuples** | Treated as the “2D ndarray” case |
| **Another DataFrame** | The DataFrame’s indexes are used unless different ones are passed |
| **NumPy MaskedArray** | Like the “2D ndarray” case except masked values are missing in the DataFrame result |

# Index Objects

* pandas's index objects are responsible for holding of the axis label (including DataFrame's column names) and other metadata (like the axis names or names).

* Index objects are immutable and cannot be modified by the user.

### Some useful Index method and properties

| Method/Property | Description |
| :--- | :--- |
| `append()` | Concatenate with additional Index objects, producing a new Index |
| `difference()` | Compute set difference as an Index |
| `intersection()` | Compute set intersection |
| `union()` | Compute set union |
| `isin()` | Compute Boolean array indicating whether each value is contained in the passed collection |
| `delete()` | Compute new Index with element at Index i deleted |
| `drop()` | Compute new Index by deleting passed values |
| `insert()` | Compute new Index by inserting element at Index i |
| `is_monotonic` | Returns True if each element is greater than or equal to the previous element |
| `is_unique` | Returns True if the Index has no duplicate values |
| `unique()` | Compute the array of unique values in the Index |

In [ ]:
import numpy as np
import pandas as pd

obj = pd.Series(np.arange(3), index = ['a','b','c'])
obj.index[1:]

Index(['b', 'c'], dtype='object')

In [ ]:
index[1] = 'd' #indexes are immutable

NameError: name 'index' is not defined

In [ ]:
Index = obj.index
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [ ]:
obj2 = pd.Series([1.5,-2.5,0],index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [ ]:
import numpy as np
import pandas as pd

obj = pd.Series([4.5,7.2,-5.3,3.6], index = ["d", "b", "a", "c"])

obj2 = obj.reindex(["a", "b", "c", "d", "e"]) # Reindexing the object

print(obj)
print(obj2)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64
a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [ ]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0,2,4])
print(obj3)
# For ordered data like time series, we can do filling using a method as "ffill", which forward-fills the values
obj3.reindex(np.arange(6), method="ffill")

0      blue
2    purple
4    yellow
dtype: object

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.arange(9).reshape((3,3)),index = ["a", "c", "d"], columns = ["Ohio", "Texas", "California"])
df

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [ ]:
df2 = df.reindex(index = ["a", "b", "c", "d"])


df2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [ ]:
states =  ["Texas", "Utah", "California"]

df.reindex(columns = states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

# Soring and Ranking

```python
# Sorting rows alphabetically/numerically by index
df.sort_index(ascending=True)

# Sorting columns alphabetically
df.sort_index(axis=1)
```

```python
df.sort_values(by=['column1', 'column2'], ascending=[True, False])
```

* Ranking in pandas is the process of assigning a numerical score to each element in a dataset based on its position relative to others.

1. The df.rank() method
Parameters:
* axis: Rank across rows(axis = 0) or columns(axis = 1)
* ascending: If false, the largest value gets the rank 1 (best for top 10 list)
* pct: If true, it returns the rank as percentile.

2. Handling ties:

When two values are identical then pandas provide following steps:

| Method | Description | Example (Values: 10, 20, 20, 30) |
| :--- | :--- | :--- |
| `average` | (Default) Assigns the average of the ranks that would have been assigned. | 1, 2.5, 2.5, 4 |
| `min` | Uses the lowest rank for the whole group (Competition ranking). | 1, 2, 2, 4 |
| `max` | Uses the highest rank for the whole group. | 1, 3, 3, 4 |
| `first` | Assigns ranks in the order they appear in the data. | 1, 2, 3, 4 |
| `dense` | Like `min`, but the next rank after a tie is the next integer (no gaps). | 1, 2, 2, 3 |

3. Ranking with Groupby:

```python
df['Group_Rank'] = df.groupby('Classroom')['Score'].rank(ascending=False)
```

In [6]:
import pandas as pd

data = {'Sales': [100, 250, 250, 500, 50]}
df = pd.DataFrame(data)

# Rank 1 being the highest seller using 'dense' to avoid skipping numbers
df.rank(ascending=False, method = 'dense')

   Sales
0    3.0
1    2.0
2    2.0
3    1.0
4    4.0

# Descriptive Statistics

| Method | Description |
| :--- | :--- |
| `count` | Number of non-NA values |
| `describe` | Compute set of summary statistics |
| `min`, `max` | Compute minimum and maximum values |
| `argmin`, `argmax` | Compute index locations (integers) at which minimum or maximum value is obtained; not available on DataFrame objects |
| `idxmin`, `idxmax` | Compute index labels at which minimum or maximum value is obtained |
| `quantile` | Compute sample quantile ranging from 0 to 1 (default: 0.5) |
| `sum` | Sum of values |
| `mean` | Mean of values |
| `median` | Arithmetic median (50% quantile) of values |
| `mad` | Mean absolute deviation from mean value |
| `prod` | Product of all values |
| `var` | Sample variance of values |
| `std` | Sample standard deviation of values |
| `skew` | Sample skewness (third moment) of values |
| `kurt` | Sample kurtosis (fourth moment) of values |
| `cumsum` | Cumulative sum of values |
| `cummin`, `cummax` | Cumulative minimum or maximum of values, respectively |
| `cumprod` | Cumulative product of values |
| `diff` | Compute first arithmetic difference (useful for time series) |
| `pct_change` | Compute percent changes |

In [11]:
import numpy as np
import pandas as pd

df = pd.DataFrame([[1.4, np.nan],[7.1, -4.5],[np.nan, np.nan], [0.75, -1.3]],
                  index = ['a','b','c','d'],
                  columns = ['one', 'two'])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [16]:
print("--- Sum over rows----")
print(df.sum()) # sum method returns the Series containing column sums unless specified specified with the axis
print("--- Sum over columns----")
print(df.sum(axis = 'columns'))

--- Sum over rows----
one    9.25
two   -5.80
dtype: float64
--- Sum over columns----
a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [21]:
print(df.sum(axis = 'index', skipna= False)) #When skipna is true then it will skip the NA values and add all the other values. But if false will return the result to be NA

print(df.sum(axis = 'columns', skipna = False))

one   NaN
two   NaN
dtype: float64
a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [22]:
# Some aggregate functions, like mean, require at least one non-NA values to get the result.

df.mean(axis = 'columns')

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [24]:
# Some method such as idmin and idmax (called Indirect Statics) return the values of the axis where the min and max are located.

df.idxmin()

one    d
two    b
dtype: object

In [25]:
# Accumulation over the process can be performed using cumulative sum, min, max and so on.

df.cumsum()

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [26]:
df.cummin()  # NA will be excluded in the process or forwarded to the next one.

    one  two
a  1.40  NaN
b  1.40 -4.5
c   NaN  NaN
d  0.75 -4.5

# Unique Values, Value Counts, and Membership

1. unique() and nunique():
- unique(): Returns an array of the unique values in the order they appear. It does not sort them.
- nunique(): Returns the number of unique values. By default, it ignores NaN values (use dropna=False to include them).

2. Frequency Counts: value_counts(): It counts how many times each unique value appears.
* By default, the result is sorted by frequency (highest first)
* Set normalize=True to get the relative frequencies (percentages) instead of raw counts

3. Membership: isin(): The isin() method is a highly efficient way to check if values in a Series or DataFrame exist within a provided list, set, or another Series. It returns a boolean mask (True/False).

4. The "Index" Connection: Index.get_indexer(): If you have a list of items and want to know their integer positions in another index, you use get_indexer.
```python
# Match unique values to a reference list to get their positions
obj = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
uniques = pd.Series(['c', 'b', 'a'])

pd.Index(uniques).get_indexer(obj)
# Output: array([0, 2, 1, 1, 0, 2])
```