<a href="https://colab.research.google.com/github/varunptel/Pythoning/blob/main/Python_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![pandas_white.svg]()

# Brief History

* The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008. It has function to analyse, clean, explore and manipulate the data.
* It helps to work with large datasets and find the results based on statistical theories.
* Pandas can clean the messy datasets, and make them readable and relevant.
* Pandas can also delete the rows that are not relevant, or containing wrong values, like empty or NULL values. This is called the cleaning the data.

* Pandas is a labeled, columnar, Numpy-backed relational engine with a sophisticated block-oriented memory manager.

* It is a BlockManager that stores heterogeneous data in homogeneous blocks for cache efficiency.

In [3]:
import numpy as np
import pandas as pd

print("Pandas version:", pd.__version__)
print("Numpy version:", np.__version__)

Pandas version: 2.2.2
Numpy version: 2.0.2

# pandas Data Structures

Data structures in pandas: Series and DataFrame

### Series: It is a one dimensional array-like object containing a sequence of values of the same type and an associated array of data labels, called its index.

In [2]:
import pandas as pd

obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
print(obj.array)
print(obj.index) #pandas has default indexing start with 0 otherwise mentioned

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64
RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([4, 7, -5, 3], index=['a','b','c','d'])
obj2

a    4
b    7
c   -5
d    3
dtype: int64

* Another way to think about the Series as a fixed-length, ordered dictionary as it represents a mapping of index values to the data values.

* We can override the key values in the series values using dictionary keys.

In [10]:
dict_data = {"x": 35000, "y": 71000, "z": 16000, "u": 5000}
obj3 = pd.Series(dict_data)
obj3

x    35000
y    71000
z    16000
u     5000
dtype: int64

In [15]:
new_ind = ["a","b","x","y"]
dict_data = {"x": 35000, "y": 71000, "z": 16000, "u": 5000}

obj4 = pd.Series(dict_data, index = new_ind)
# Here it will replace the two values found from the original dictionary but appear as NaN(Not a Number) for other values.
obj4

a        NaN
b        NaN
x    35000.0
y    71000.0
dtype: float64

In [17]:
print(obj3)
obj3.index = ["a","b","c","d"]
# Index alteration
print(obj3)

a    35000
b    71000
c    16000
d     5000
dtype: int64
a    35000
b    71000
c    16000
d     5000
dtype: int64