# Data Clearning and Preparations using pandas

### Handling Missing Data:
For data with float64 dtype, pandas uses the floating-point value NaN (Not a Number) to represent missing data.

In [3]:
import numpy as np
import pandas as pd

float_data = pd.Series([1.2, -3.5, np.nan, 0])
print(float_data)
print(float_data.isna())

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64
0    False
1    False
2     True
3    False
dtype: bool

### Filtering Out missing Data

| Method | Description |
| :--- | :--- |
| `dropna` | Filter axis labels based on whether values for each label have missing data, with varying thresholds for how much missing data to tolerate. |
| `fillna` | Fill in missing data with some value or using an interpolation method such as `"ffill"` or `"bfill"`. |
| `isna` | Return Boolean values indicating which values are missing/NA. |
| `notna` | Negation of `isna`; returns `True` for non-NA values and `False` for NA values. |

In [5]:
data = pd.Series([1,np.nan, 0, np.nan, 7])
print(data)
print(data.dropna())

0    1.0
1    NaN
2    0.0
3    NaN
4    7.0
dtype: float64
0    1.0
2    0.0
4    7.0
dtype: float64

In [8]:
df = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                   [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

print(df)
print(df.dropna(how="all"))  # how="all" will drop only rows that are all NA

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0
     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [9]:
# Lets add column 4 with all NA values
df[4] = np.nan
df

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [10]:
df.dropna(axis = 'columns', how = 'all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [15]:
df = pd.DataFrame(np.random.standard_normal((7,3)))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

          0         1         2
0 -0.247181       NaN       NaN
1  0.266390       NaN       NaN
2  2.470172       NaN  1.025969
3 -1.108328       NaN  0.724367
4  0.845953 -0.353361 -0.888245
5  1.627867 -1.477636 -1.612831
6 -1.863728 -0.520584  0.478554

In [16]:
df.dropna()

          0         1         2
4  0.845953 -0.353361 -0.888245
5  1.627867 -1.477636 -1.612831
6 -1.863728 -0.520584  0.478554

In [17]:
df.dropna(thresh = 2)

          0         1         2
2  2.470172       NaN  1.025969
3 -1.108328       NaN  0.724367
4  0.845953 -0.353361 -0.888245
5  1.627867 -1.477636 -1.612831
6 -1.863728 -0.520584  0.478554

### Filling in Missing Data

fillna function arguments:
| Argument | Description |
| :--- | :--- |
| **value** | Scalar value or dictionary-like object to use to fill missing values. |
| **method** | Interpolation method: one of `"bfill"` (backward fill) or `"ffill"` (forward fill); default is `None`. |
| **axis** | Axis to fill on (`"index"` or `"columns"`); default is `axis="index"`. |
| **limit** | For forward and backward filling, maximum number of consecutive periods to fill. |

In [19]:
# Filling in missing data

df.fillna(0) # replaces the NA values with the scalar value 0

          0         1         2
0 -0.247181  0.000000  0.000000
1  0.266390  0.000000  0.000000
2  2.470172  0.000000  1.025969
3 -1.108328  0.000000  0.724367
4  0.845953 -0.353361 -0.888245
5  1.627867 -1.477636 -1.612831
6 -1.863728 -0.520584  0.478554

In [20]:
# calling fillna with dictionary, we can replace different value for different columns

df.fillna({1: 0.5, 2: 0})

          0         1         2
0 -0.247181  0.500000  0.000000
1  0.266390  0.500000  0.000000
2  2.470172  0.500000  1.025969
3 -1.108328  0.500000  0.724367
4  0.845953 -0.353361 -0.888245
5  1.627867 -1.477636 -1.612831
6 -1.863728 -0.520584  0.478554

In [23]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

          0         1         2
0 -0.191197 -1.421806 -0.350600
1  0.529431 -1.213956  0.000316
2  0.109753       NaN -1.739093
3 -1.445380       NaN  1.031774
4  1.573826       NaN       NaN
5  0.146884       NaN       NaN

In [26]:
print(df.fillna(method = 'ffill'))
print(df.fillna(method = 'ffill', limit = 2))

          0         1         2
0 -0.191197 -1.421806 -0.350600
1  0.529431 -1.213956  0.000316
2  0.109753 -1.213956 -1.739093
3 -1.445380 -1.213956  1.031774
4  1.573826 -1.213956  1.031774
5  0.146884 -1.213956  1.031774
          0         1         2
0 -0.191197 -1.421806 -0.350600
1  0.529431 -1.213956  0.000316
2  0.109753 -1.213956 -1.739093
3 -1.445380 -1.213956  1.031774
4  1.573826       NaN  1.031774
5  0.146884       NaN  1.031774

/tmp/ipykernel_855/2362543477.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method = 'ffill'))
/tmp/ipykernel_855/2362543477.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method = 'ffill', limit = 2))

In [28]:
# We can do a lot of things with the fillna() method

data = pd.Series([1, np.nan, 3.5, np.nan, 7])

data = data.fillna(data.mean())
data

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64