# Data Clearning and Preparations using pandas

### Handling Missing Data:
For data with float64 dtype, pandas uses the floating-point value NaN (Not a Number) to represent missing data.

In [ ]:
import numpy as np
import pandas as pd

float_data = pd.Series([1.2, -3.5, np.nan, 0])
print(float_data)
print(float_data.isna())

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64
0    False
1    False
2     True
3    False
dtype: bool

### Filtering Out missing Data

| Method | Description |
| :--- | :--- |
| `dropna` | Filter axis labels based on whether values for each label have missing data, with varying thresholds for how much missing data to tolerate. |
| `fillna` | Fill in missing data with some value or using an interpolation method such as `"ffill"` or `"bfill"`. |
| `isna` | Return Boolean values indicating which values are missing/NA. |
| `notna` | Negation of `isna`; returns `True` for non-NA values and `False` for NA values. |

In [ ]:
data = pd.Series([1,np.nan, 0, np.nan, 7])
print(data)
print(data.dropna())

0    1.0
1    NaN
2    0.0
3    NaN
4    7.0
dtype: float64
0    1.0
2    0.0
4    7.0
dtype: float64

In [ ]:
df = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                   [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

print(df)
print(df.dropna(how="all"))  # how="all" will drop only rows that are all NA

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0
     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
# Lets add column 4 with all NA values
df[4] = np.nan
df

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [ ]:
df.dropna(axis = 'columns', how = 'all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
df = pd.DataFrame(np.random.standard_normal((7,3)))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

          0         1         2
0 -0.247181       NaN       NaN
1  0.266390       NaN       NaN
2  2.470172       NaN  1.025969
3 -1.108328       NaN  0.724367
4  0.845953 -0.353361 -0.888245
5  1.627867 -1.477636 -1.612831
6 -1.863728 -0.520584  0.478554

In [ ]:
df.dropna()

          0         1         2
4  0.845953 -0.353361 -0.888245
5  1.627867 -1.477636 -1.612831
6 -1.863728 -0.520584  0.478554

In [ ]:
df.dropna(thresh = 2)

          0         1         2
2  2.470172       NaN  1.025969
3 -1.108328       NaN  0.724367
4  0.845953 -0.353361 -0.888245
5  1.627867 -1.477636 -1.612831
6 -1.863728 -0.520584  0.478554

### Filling in Missing Data

fillna function arguments:
| Argument | Description |
| :--- | :--- |
| **value** | Scalar value or dictionary-like object to use to fill missing values. |
| **method** | Interpolation method: one of `"bfill"` (backward fill) or `"ffill"` (forward fill); default is `None`. |
| **axis** | Axis to fill on (`"index"` or `"columns"`); default is `axis="index"`. |
| **limit** | For forward and backward filling, maximum number of consecutive periods to fill. |

In [ ]:
# Filling in missing data

df.fillna(0) # replaces the NA values with the scalar value 0

          0         1         2
0 -0.247181  0.000000  0.000000
1  0.266390  0.000000  0.000000
2  2.470172  0.000000  1.025969
3 -1.108328  0.000000  0.724367
4  0.845953 -0.353361 -0.888245
5  1.627867 -1.477636 -1.612831
6 -1.863728 -0.520584  0.478554

In [ ]:
# calling fillna with dictionary, we can replace different value for different columns

df.fillna({1: 0.5, 2: 0})

          0         1         2
0 -0.247181  0.500000  0.000000
1  0.266390  0.500000  0.000000
2  2.470172  0.500000  1.025969
3 -1.108328  0.500000  0.724367
4  0.845953 -0.353361 -0.888245
5  1.627867 -1.477636 -1.612831
6 -1.863728 -0.520584  0.478554

In [ ]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

          0         1         2
0 -0.191197 -1.421806 -0.350600
1  0.529431 -1.213956  0.000316
2  0.109753       NaN -1.739093
3 -1.445380       NaN  1.031774
4  1.573826       NaN       NaN
5  0.146884       NaN       NaN

In [ ]:
print(df.fillna(method = 'ffill'))
print(df.fillna(method = 'ffill', limit = 2))

          0         1         2
0 -0.191197 -1.421806 -0.350600
1  0.529431 -1.213956  0.000316
2  0.109753 -1.213956 -1.739093
3 -1.445380 -1.213956  1.031774
4  1.573826 -1.213956  1.031774
5  0.146884 -1.213956  1.031774
          0         1         2
0 -0.191197 -1.421806 -0.350600
1  0.529431 -1.213956  0.000316
2  0.109753 -1.213956 -1.739093
3 -1.445380 -1.213956  1.031774
4  1.573826       NaN  1.031774
5  0.146884       NaN  1.031774

/tmp/ipykernel_855/2362543477.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method = 'ffill'))
/tmp/ipykernel_855/2362543477.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method = 'ffill', limit = 2))

In [ ]:
# We can do a lot of things with the fillna() method

data = pd.Series([1, np.nan, 3.5, np.nan, 7])

data = data.fillna(data.mean())
data

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

### Data Transformation

There are several methods linked to the data transformations

1) Removing Duplicates:
* drop_duplicates() returns a DataFrame with rows where the duplicated array is False filtered out.
* These methods by default considers all the columns, we can specify the subset to them to detect the duplicates.

In [ ]:
import pandas as pd
import numpy as np

data = pd.DataFrame({'k1':['one','two'] * 3 + ['two'],
                     'k2':[1,1,2,3,3,4,4]})
print(data)
print(data.duplicated()) # Returns boolean value for duplicated rows

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4
0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [ ]:
print(data.drop_duplicates())

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [ ]:
data['v1'] = range(7)
print(data)
print(data.drop_duplicates(subset = ['k1'])) # duplicated values are dropped in k1 column
print(data.drop_duplicates(subset = ['k1', 'k2'], keep = 'last')) # duplicated values are dropped in k1 and k2 columns while keeping the last value instead of the first

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6
    k1  k2  v1
0  one   1   0
1  two   1   1
    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

2. Transforming Data Using a Function or Mapping
* The map function on a series accepts the function of dictionary like key-value pair of values to do the transformation.

In [ ]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [ ]:
meat_to_animal = {
 "bacon": "pig",
 "pulled pork": "pig",
 "pastrami": "cow",
 "corned beef": "cow",
 "honey ham": "pig",
 "nova lox": "salmon"
} # mapping function

In [ ]:
data['animal'] = data['food'].map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

3. Replacing Values

In [2]:
import pandas as pd
import numpy as np

data = pd.Series([1, -999., 2, -999., -1000, 3])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [3]:
data.replace(-999, np.nan) # replacing -999 with NA values

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [8]:
data.replace([-999, -1000], [np.nan, 0]) # Replacing multiple values
data.replace({-999: np.nan, -1000: 0})  # THis is same thing as above but with dict like object

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

3. Renaming the Axis Indexes

* One of the way to rename the axis by mapping a function onto the original values.
* If we want transformed version without modifying the dataset is by using the method of rename()

In [3]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.arange(12).reshape(3,4),
                  index = ['Ohio', 'Colorado', 'New York'],
                  columns = ['one', 'two', 'three', 'four'])

df

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [4]:
def transform(x):
  return x[:4].upper()

df.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [6]:
df.index = df.index.map(transform)
df

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [7]:
df.rename(index = str.title, columns = str.upper)

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [8]:
df.rename(index = {'OHIO': "INDIANA"},
          columns = {'three': 'This'}
          )

         one  two  This  four
INDIANA    0    1     2     3
COLO       4    5     6     7
NEW        8    9    10    11